site_name: FTC Electronics 
theme:
  name: material
  logo: assets/
  palette:
    scheme: slate
    primary: black
  features:
    - navigation.indexes
    - navigation.sarch false
nav:
  - Home: index.md 
  - Wiring: 
    - wiring/index.md
    - wiring/routing.md
    - wiring/protection.md
    - wiring/moving.md
    - wiring/custom.md
  - Sensors: sensors.md
  - PCBs: pcbs.md
  - About: about.md
extra:
  generator: false
plugins:
      - search:
          enabled: false