site_name: FTC Electronics 
theme:
  name: material
  palette:
    scheme: slate
    primary: black
  features:
    - navigation.sidebar

nav:
  - Home: index.md 
  - Introduction: introduction.md
  - Wiring: wiring.md
  - Sensors: sensors.md
  - PCB's: pcbs.md
  - About: about.md
extra:
  generator: false